module.exports = {
  GET_ALL_FILES: 'GET_ALL_FILES',
  RECEIVE_ALL_FILES: 'RECEIVE_ALL_FILES',
  GET_CURRENT_FILE: 'GET_CURRENT_FILE',
  RECEIVE_FILE_CONTENT: 'RECEIVE_FILE_CONTENT',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  REMOVE_HIGHLIGHT: 'REMOVE_HIGHLIGHT'
};